[test]
coverage = true         # Always enable coverage
coverageThreshold = 0.8 # Fail if coverage is below 80%

[install.scopes]
"@edgefirst-dev" = { url = "https://npm.pkg.github.com", token = "$GITHUB_TOKEN" }
