name = "edgefirst-dev-starter"

main = "./worker.ts"

# Update the compatibility date to the date you want to lock to
compatibility_date = "2024-10-11"

# This is needed for AsyncLocalStorage to work
compatibility_flags = ["nodejs_compat"]

dev.port = 3000

assets = { directory = "./build/client", binding = "ASSETS" }

# To be able to use assets in your Worker, Smart placement needs to be off
[placement]
mode = "off"

# Enable Observability to get logs of your Worker
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "stack-db"
database_id = "e746a19d-d890-4321-9c30-5167828540a2"
migrations_dir = "./db/migrations"

[[kv_namespaces]]
binding = "KV"
id = "1473f4ea43174ad5853a017f8fde1f37"

[[r2_buckets]]
binding = "FS"
bucket_name = "stack-blob"

[[queues.producers]]
queue = "edgefirst-queue"
binding = "QUEUE"

[[queues.consumers]]
queue = "edgefirst-queue"

[ai]
binding = "AI"

# Uncomment to enable cron jobs
# [triggers]
# crons = ["* * * * *"]
