name: Deploy

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    name: "Deploy to Cloudflare Workers"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci

      - name: Run migrations
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: |
            npm run db:migrate ${{ secrets.CLOUDFLARE_DATABASE_NAME }}
